version: '3'
services:
  app:
    build: .
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - 3000:8080
    command: npm run start
    links:
      - mongo
  mongo:
    image: mongo
    # ports:
    #   - 27017:27017
    # volumes:
    #   - ./data/db:/data/db