version: '3'
services:
  app:
    build: .
    restart: always    
    # depends_on:
    #   - mongo
    environment:
      NODE_ENV: development
    ports:
      - '3000:3000'
    command: npm run start
    # links:
    #   - mydb
    networks: 
      backend_ops:
        aliases: ["app.ops.local"]

  mydb:
    container_name: mongo
    restart: always
    image: mongo
    restart: always
    ports:
      - 27624:27624
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    volumes:
      - /var/lib/docker/volumes
    command: mongod --smallfiles --logpath=/dev/null
    networks: 
      backend_ops:
        aliases: ["mydb.ops.local"]
    # volumes:
    #   - ./data/db:/data/db

networks: 
  backend_ops:
    driver: bridge